root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:astro/recommended
  - plugin:astro/jsx-a11y-recommended
overrides:
  - files: ["*.astro"]
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: [".astro"]
