name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.29.1"
      - name: Create JavaScript bundle
        run: deno bundle src/index.ts public/index.js
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public