name: CD

on:
  push:
    branches:
      - main
    paths:
      - src
      - public
      - scripts

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.3.0"
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/dist
          # Generate a new cache whenever packages or source files change.
          key: ci-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.ts') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ci-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Build static site
        run: pnpm build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v2
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
  deploy:
    name: Deploy to GitHub pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
