name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - src
      - public
      - scripts
      - Dockerfile
      - nginx/Dockerfile

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.3.0"
          cache: pnpm
      - name: Install dependencies
        run: pnpm i
      - name: Run linter
        run: pnpm eslint .
      - name: Check formatting
        run: pnpm prettier --check .
      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/dist
          # Generate a new cache whenever packages or source files change.
          key: ci-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.ts') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ci-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Build source
        run: pnpm tsc
