name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install playwright browsers
        run: pnpm dlx playwright install --with-deps
      - name: Run tests
        run: |
          astro build
          pnpm dlx playwright test
